name: github_issue_tracker
description: "GitHub Issue Tracker app that allows users to track issues across multiple GitHub repositories. The app should provide a centralized interface for viewing, and searching issues."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.1.2
  github_oauth: ^0.0.2
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3+1
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.5
  loading_animation_widget: ^1.2.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/logo/
    - assets/lottie/
    - assets/icons/
